-- begin PETCLININC_PET
alter table PETCLININC_PET add constraint FK_PETCLININC_PET_ON_PET_TYPE foreign key (PET_TYPE_ID) references PETCLININC_PET_TYPE(ID)^
alter table PETCLININC_PET add constraint FK_PETCLININC_PET_ON_OWNER foreign key (OWNER_ID) references PETCLININC_OWNER(ID)^
alter table PETCLININC_PET add constraint FK_PETCLININC_PET_ON_CATEGORY foreign key (CATEGORY_ID) references SYS_CATEGORY(ID)^
create index IDX_PETCLININC_PET_ON_PET_TYPE on PETCLININC_PET (PET_TYPE_ID)^
create index IDX_PETCLININC_PET_ON_OWNER on PETCLININC_PET (OWNER_ID)^
create index IDX_PETCLININC_PET_ON_CATEGORY on PETCLININC_PET (CATEGORY_ID)^
-- end PETCLININC_PET
-- begin PETCLININC_VISIT
alter table PETCLININC_VISIT add constraint FK_PETCLININC_VISIT_ON_PET foreign key (PET_ID) references PETCLININC_PET(ID)^
alter table PETCLININC_VISIT add constraint FK_PETCLININC_VISIT_ON_VETERINARIAN foreign key (VETERINARIAN_ID) references PETCLININC_VETERINARIAN(ID)^
create index IDX_PETCLININC_VISIT_ON_PET on PETCLININC_VISIT (PET_ID)^
create index IDX_PETCLININC_VISIT_ON_VETERINARIAN on PETCLININC_VISIT (VETERINARIAN_ID)^
-- end PETCLININC_VISIT
-- begin PETCLININC_OWNER
create unique index IDX_PETCLININC_OWNER_UK_PHONE_NO on PETCLININC_OWNER (PHONE_NO) where DELETE_TS is null ^
create unique index IDX_PETCLININC_OWNER_UK_EMAIL on PETCLININC_OWNER (EMAIL) where DELETE_TS is null ^
-- end PETCLININC_OWNER
-- begin PETCLININC_VETERINARIAN
alter table PETCLININC_VETERINARIAN add constraint FK_PETCLININC_VETERINARIAN_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_PETCLININC_VETERINARIAN_ON_USER on PETCLININC_VETERINARIAN (USER_ID)^
-- end PETCLININC_VETERINARIAN
-- begin PETCLININC_VISIT_CONSUMABLE_LINK
alter table PETCLININC_VISIT_CONSUMABLE_LINK add constraint FK_VISCON_ON_VISIT foreign key (VISIT_ID) references PETCLININC_VISIT(ID)^
alter table PETCLININC_VISIT_CONSUMABLE_LINK add constraint FK_VISCON_ON_CONSUMABLE foreign key (CONSUMABLE_ID) references PETCLININC_CONSUMABLE(ID)^
-- end PETCLININC_VISIT_CONSUMABLE_LINK
