alter table PETCLININC_PET add constraint FK_PETCLININC_PET_ON_CATEGORY foreign key (CATEGORY_ID) references SYS_CATEGORY(ID);
create index IDX_PETCLININC_PET_ON_CATEGORY on PETCLININC_PET (CATEGORY_ID);
